# Generated by Django 5.1.5 on 2025-02-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('matkhau', models.CharField(max_length=255)),
                ('vaitro', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Customer', 'Customer')], default='Customer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LichDatSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batdau', models.DateTimeField()),
                ('ketthuc', models.DateTimeField()),
                ('loaisan', models.CharField(max_length=50)),
                ('madon', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('taikhoan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminsystem.taikhoan')),
            ],
            bases=('adminsystem.taikhoan',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('taikhoan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminsystem.taikhoan')),
                ('makhachhang', models.CharField(max_length=20, unique=True)),
            ],
            bases=('adminsystem.taikhoan',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('taikhoan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminsystem.taikhoan')),
            ],
            bases=('adminsystem.taikhoan',),
        ),
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadon', models.CharField(max_length=20, unique=True)),
                ('thanhtoan_thanhcong', models.BooleanField(default=False)),
                ('thongtin_donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsystem.lichdatsan')),
            ],
        ),
        migrations.AddField(
            model_name='lichdatsan',
            name='thongtin_khachhang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsystem.customer'),
        ),
    ]
